# 购买者条约:
# 作者: Brayn_lzh
# QQ: 390807154
# 保修规则:
#   插件永久修复错误(在合理程度内 非买方误操作 非服务端本身问题)
#   包1年内MC版本更替修复(部分情况会延保1年)
#   对修改过代码的不保修
#   需要保修时请说明问题 务必附上报错内容
#   若需要添加新功能将进行最低量的收费
# 你可以:
#   1.声明这个插件是私用的
#   2.举报他人服务器剽窃该插件
#   3.利用本插件盈利
#   4.修改本插件代码
# 你不可以:
#   1.声明这个插件是你写的
#   2.不能通过卖本插件盈利
# 对应不在本条约里的事项请向我联系
name: GenericAttribute
authors: ['Bryan_lzh']
main: Br.GenericAttribute.Main
version: 1.0-release

commands:
  GenericAttributeGet:
    aliases: [gaget]
    description: 主命令
    usage: /<command>
  GenericAttribute:
    aliases: [ga]
    description: 主命令
    usage: /<command>