Eq1:
    Name: '&c赤心套装'
    Lore:
        - '&61个套装:无效果'
        - '&62个套装:攻击力+5,吸血+3'
        - '&63个套装:生命值低于10%时，生成一个最大生命值40%的护盾，冷却20秒'
        - '&6       生命值低于10%时，给自己一个10秒的无敌，冷却50秒'
        - '&6       防御+5'
        - '&61个套装:永久药水效果 速度提升2'
    Effect:
        '1': 'None'
        '2': 'Attr:[Atk:5,Vampire:3]'
        '3': 'Skill:[Shield:10&40&20,Unstoppable:10&10&50]|Attr:[Def:5]'
        '4': 'Skill:[Buff:1&1]'
    